services:
  bigtic:
    image: ${DOCKER_REGISTRY-}bigtic
    build:
      context: BigTic
      dockerfile: Dockerfile
    environment:
      - DB_SERVER=sql-server2022
  sql:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: sql-server2022
    ports: # not actually needed, because the two services are on the same network
      - "1433:1433" 
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=A&VeryComplex123Password
